<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertia.xacro"/>

    <xacro:macro name="base_xacro" params="length radius">
        <!-- 虚拟部件(用于贴合地面) -->
        <link name="base_footprint"/>
            
        <!-- 机器人身体部分 -->
        <link name="base_link">
            <!-- 部件的外观描述 -->
            <visual>
                <!-- 沿着自己几何中心的偏移和旋转 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                    <!-- 圆柱体 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="">
                    <color rgba="0.0 1.0 0.0 0.5"/>
                </material>
            </visual>
            <collision>
                <!-- 沿着自己几何中心的偏移和旋转 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                    <!-- 圆柱体 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="Green">
                    <color rgba="0.0 1.0 0.0 0.5"/>
                </material>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
        </link>

        <joint name="joint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />
            <origin xyz="0 0 ${length/2.0+0.032-0.001}" rpy="0 0 0" />
        </joint>

        <gazebo reference="base_link">
            <material>Gazebo/Green</material>
        </gazebo>

    </xacro:macro>
    
</robot>
